---
- hosts: centos
  vars:
    date_time: "{{ansible_date_time.date}} {{ansible_date_time.hour}}:{{ansible_date_time.minute}}"

  tasks:
  - name: wirte date run to a fileon the server 
    template: src=date_template.j2 dest=/home/ansible/date-time.txt
    
